### ISSUE TITLE
Why not use Exit(0) but we use return 0

### ISSUE THREAD

**Issue by thanhluan001** [armandooj/NachOS#11]
Maybe Armendo can explain this to me but we define SC_Exit but why do we use return 0 at the end? Shouldn't it be Exit(0) at the end? 

And also in the Assembly code,  $4 has the the return value and $2 has the type of syscal we need to do?

**Comment by armandooj** [comment]
@thanhluan001 The only reason to use return is that for me it makes more sense since that's how C programs usually end. But I agree, we could aso use Exit(0).

You're right. 2: type, 4: return value. I chose 4 but we can use any (free) register to store the return value. We would need to change move $4, $2.
